apiVersion: v1
kind: Service
metadata:
  labels:
    app: payments-mongo
  name: payments-mongo-svc
spec:
  ports:
    - port: 27017
      protocol: TCP
  selector:
    app: payments-mongo
  clusterIP: None
